[package]
name = "obfstr2"
version = "0.1.1"
edition = "2024"
resolver = "2"
description = "Polymorphic compile-time string/bytes/file obfuscation"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ZEROLINGG/obfstr2"


[dependencies]
obfstr2-macros = { version = "0.1", path = "obfstr2-macros" }
lib-unknown = { version = "0.1", default-features = false, features = ["crypto", "types"] }


[features]
default = [
    "lib-unknown/alloc",
    "obfstr2-macros/alloc"
]
