[package]
name = "obfstr2"
version = "0.1.11-preview"
edition = "2024"
resolver = "2"
rust-version = "1.98"
description = "Polymorphic compile-time string/bytes/int/float/cstr/file obfuscation"
license = "MIT"
readme = "README.md"
repository = "https://github.com/ZEROLINGG/obfstr2"
keywords = ["obfuscation", "string", "no-std", "compile-time", "polymorphic"]
categories = ["no-std", "embedded"]


[dependencies]
obfstr2-macros = { version = "=0.1.11-preview", path = "obfstr2-macros" }
lib-unknown = { version = "0.1.6", default-features = false, features = ["crypto", "types"] }


[features]
default = [
    "lib-unknown/alloc",
    "obfstr2-macros/alloc"
]

[dev-dependencies]
lib-unknown = { version = "0.1.6", features = ["dyntest", "std"] }
